sudo: required
services:
  - docker

before_install:
  - docker build -t viettran1010/docker-react -f Dockerfile.dev .

script: 
  - docker run viettran1010/docker-react yarn test -- --coverage --watchAll=false --detectOpenHandles

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "react-docker-env"
  env: "Reactdockerenv-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-714604073986"
  bucket_path: "react-docker-env"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY
